typedef void R_TYPE, ARG1_TYPE, ARG2_TYPE, ARG3_TYPE, ARG4_TYPE;

R_TYPE FN_NAME(ARG1_TYPE ARG1, ARG2_TYPE ARG2, ARG3_TYPE ARG3, ARG4_TYPE ARG4)
{
	R_TYPE ret;
	ret = ARG_1 + ARG_2 + ARG_3 + ARG_4;
	return ret;
}
