typedef void FUNC_TYPE, FUNC_NAME, ARG1_TYPE, ARG1_VAL, 
	ARG2_TYPE, ARG2_VAL, ARG3_TYPE, ARG3_VAL;

CSTUB_FN_ARGS_3(FUNC_TYPE FUNC_T, FUNC_NAME FUNC_N, 
		ARG1_TYPE ARG1_T, ARG1_VAL ARG1_V, 
		ARG2_TYPE ARG2_T, ARG2_VAL ARG2_V,
		ARG2_TYPE ARG3_T, ARG2_VAL ARG3_V)
{

	CSTUB_ASM_3(FUNC_N, ARG1_V, ARG2_V, ARG3_V);
	
	CSTUB_POST;
}
