typedef void R_TYPE, ARG1_TYPE, ARG2_TYPE, ARG3_TYPE, ARG4_TYPE;

R_TYPE __sg_FN_NAME(spdid_t spdid, ARG1_TYPE ARG1, ARG2_TYPE ARG2, ARG3_TYPE ARG3, ARG4_TYPE ARG4)
{
	R_TYPE ret;
	ret = FN_NAME(spdid, ARG1,  ARG2,  ARG3,  ARG4);
	return ret;
}
