typedef void FUNC_TYPE, FUNC_NAME, ARG1_TYPE, ARG1_VAL, ARG2_TYPE, ARG2_VAL;

CSTUB_FN_ARGS_2(FUNC_TYPE FUNC_T, FUNC_NAME FUNC_N, 
		ARG1_TYPE ARG1_T, ARG1_VAL ARG1_V, 
		ARG2_TYPE ARG2_T, ARG2_VAL ARG2_V)
{

	CSTUB_ASM_2(FUNC_N, ARG1_V, ARG2_V);
	
	CSTUB_POST;
}
